"""empty message

Revision ID: 1bce3fa27ee7
Revises: 
Create Date: 2019-07-30 15:53:23.239037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bce3fa27ee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), unique=True, index=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('uuid', sa.INTEGER(), server_default=sa.text("nextval('category_uuid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('association',
    sa.Column('posts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.uuid'], name='association_category_id_fkey'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.uuid'], name='association_posts_id_fkey')
    )
    op.create_table('users',
    sa.Column('uuid', sa.INTEGER(), server_default=sa.text("nextval('users_uuid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('posts',
    sa.Column('uuid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.uuid'], name='posts_author_id_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='posts_pkey')
    )
    # ### end Alembic commands ###
